# Generated by Django 4.2.19 on 2025-03-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puppy',
            name='picture_url',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to='puppy_images/'),
        ),
        migrations.AlterField(
            model_name='pupdate',
            name='media_url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='pupdate',
            name='picture_url',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to='pupdate_images/'),
        ),
    ]
