# Generated by Django 5.1.6 on 2025-03-02 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Puppies',
            new_name='Puppy',
        ),
    ]
