# Generated by Django 5.1.7 on 2025-03-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main_app', '0002_puppy_picture_url_alter_pupdate_media_url_and_more'),
    ]


