# Generated by Django 5.1.7 on 2025-03-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_puppy_picture_url_alter_pupdate_media_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsoruser',
            name='stripe_customer_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
