# Generated by Django 5.1.7 on 2025-03-16 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_puppy_picture_url_alter_pupdate_media_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsoruser',
            name='contact_pref',
        ),
    ]
