# Generated by Django 4.2.19 on 2025-03-03 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_puppies_puppy'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(8)])),
                ('pronouns', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('user_tel', models.CharField(max_length=20)),
                ('contact_pref', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spon_pups', models.ManyToManyField(to='main_app.puppy')),
            ],
        ),
    ]
