# Generated by Django 5.1.7 on 2025-03-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_sponsoruser_contact_pref'),
    ]

    operations = [
        migrations.AddField(
            model_name='puppy',
            name='is_sponsorable',
            field=models.BooleanField(default=False),
        ),
    ]
