# Generated by Django 5.1.6 on 2025-03-05 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pupdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=300)),
                ('picture_url', models.CharField(max_length=400)),
                ('media_url', models.CharField(max_length=400)),
                ('date', models.DateField(verbose_name='Pupdate date')),
                ('pup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.puppy')),
                ('user', models.ManyToManyField(blank=True, to='main_app.user')),
            ],
        ),
    ]
