# Generated by Django 5.1.7 on 2025-03-17 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_sponsoruser_stripe_customer_id'),
        ('main_app', '0004_puppy_is_sponsorable'),
    ]

    operations = [
    ]
