# Generated by Django 5.1.7 on 2025-03-18 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_sponsoruser_user_permissions'),
        ('main_app', '0005_merge_20250317_1926'),
    ]

    operations = [
    ]
