# Generated by Django 4.2.19 on 2025-03-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_publicuser_remove_pupdate_user_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicuser',
            name='contact_pref',
        ),
        migrations.RemoveField(
            model_name='publicuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='publicuser',
            name='pronouns',
        ),
        migrations.RemoveField(
            model_name='publicuser',
            name='spon_pups',
        ),
        migrations.RemoveField(
            model_name='publicuser',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='publicuser',
            name='user_tel',
        ),
        migrations.AlterField(
            model_name='publicuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='publicuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='publicuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
