# Generated by Django 5.1.7 on 2025-03-18 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_merge_20250318_2049'),
        ('main_app', '0006_sponsoruser_contact_pref_alter_sponsoruser_groups_and_more'),
    ]

    operations = [
    ]
