# Generated by Django 5.1.7 on 2025-04-14 11:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_merge_20250318_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupdate',
            name='picture_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='picture_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
