# Generated by Django 5.1.7 on 2025-05-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_pupdate_picture_url_alter_puppy_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='pronouns',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
