# Generated by Django 5.1.7 on 2025-05-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_staffuser_pronouns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsoruser',
            name='pronouns',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sponsoruser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
