# Generated by Django 5.1.7 on 2025-05-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_sponsoruser_pronouns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsoruser',
            name='address',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
